apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx-sapna1
    image: nginx:1.21.3
    ports:
    - containerPort: 8080
  - name: watcher-sapna
    image: afakharany/watcher
